-- =============================================================================
-- Todo List App — Reference DDL
-- Generated from: backend/app/models/
-- Target:         PostgreSQL 16
--
-- NOTE: This file is for reference and fresh-environment setup only.
--       In production, schema changes are managed by Alembic migrations.
--       Do not apply this file on top of an existing Alembic-managed database.
-- =============================================================================


-- ---------------------------------------------------------------------------
-- Extensions
-- ---------------------------------------------------------------------------

CREATE EXTENSION IF NOT EXISTS "pgcrypto";  -- provides gen_random_uuid()


-- ---------------------------------------------------------------------------
-- ENUM Types
-- ---------------------------------------------------------------------------

CREATE TYPE taskstatus AS ENUM (
    'todo',
    'in_progress',
    'done'
);

CREATE TYPE recurringfrequency AS ENUM (
    'weekly',
    'fortnightly',
    'monthly'
);


-- ---------------------------------------------------------------------------
-- Tables
-- (in dependency order: parent tables before child tables)
-- ---------------------------------------------------------------------------

-- users
-- Root table. All user-owned data cascades on delete.
CREATE TABLE users (
    id               UUID         NOT NULL DEFAULT gen_random_uuid(),
    email            VARCHAR(255) NOT NULL,
    hashed_password  VARCHAR      NOT NULL,
    created_at       TIMESTAMPTZ  NOT NULL DEFAULT NOW(),

    CONSTRAINT pk_users       PRIMARY KEY (id),
    CONSTRAINT uq_users_email UNIQUE      (email)
);


-- topics
-- Belongs to a user. Topic names are unique per user, not globally.
CREATE TABLE topics (
    id          UUID         NOT NULL DEFAULT gen_random_uuid(),
    user_id     UUID         NOT NULL,
    name        VARCHAR(100) NOT NULL,
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT NOW(),

    CONSTRAINT pk_topics           PRIMARY KEY (id),
    CONSTRAINT fk_topics_user      FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT uq_topics_user_name UNIQUE      (user_id, name)
);


-- tasks
-- Core domain table. status defaults to 'todo'. archived defaults to false.
-- updated_at is kept current by the trg_tasks_updated_at trigger below.
CREATE TABLE tasks (
    id           UUID        NOT NULL DEFAULT gen_random_uuid(),
    user_id      UUID        NOT NULL,
    title        VARCHAR(255) NOT NULL,
    description  TEXT,
    due_date     TIMESTAMPTZ,
    status       taskstatus  NOT NULL DEFAULT 'todo',
    result_note  TEXT,
    archived     BOOLEAN     NOT NULL DEFAULT FALSE,
    done_at      TIMESTAMPTZ,           -- set by service when status transitions to 'done'
    archived_at  TIMESTAMPTZ,           -- set by the 4am scheduler job
    manual_order INTEGER,               -- nullable; used for same-day drag-and-drop ordering
    created_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT pk_tasks      PRIMARY KEY (id),
    CONSTRAINT fk_tasks_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);


-- task_topics
-- Many-to-many join between tasks and topics.
-- Deleting either side removes the association; neither task nor topic is deleted.
CREATE TABLE task_topics (
    task_id   UUID NOT NULL,
    topic_id  UUID NOT NULL,

    CONSTRAINT pk_task_topics        PRIMARY KEY (task_id, topic_id),
    CONSTRAINT fk_task_topics_task   FOREIGN KEY (task_id)  REFERENCES tasks  (id) ON DELETE CASCADE,
    CONSTRAINT fk_task_topics_topic  FOREIGN KEY (topic_id) REFERENCES topics (id) ON DELETE CASCADE
);


-- refresh_tokens
-- Stores hashed refresh tokens for JWT revocation on logout.
-- token_hash is a SHA-256 hex digest (64 chars) of the raw token.
CREATE TABLE refresh_tokens (
    id          UUID        NOT NULL DEFAULT gen_random_uuid(),
    user_id     UUID        NOT NULL,
    token_hash  VARCHAR(64) NOT NULL,
    expires_at  TIMESTAMPTZ NOT NULL,
    revoked     BOOLEAN     NOT NULL DEFAULT FALSE,

    CONSTRAINT pk_refresh_tokens      PRIMARY KEY (id),
    CONSTRAINT fk_refresh_tokens_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);


-- recurring_templates
-- Source definition for recurring tasks. Instances are generated by the scheduler.
-- Setting is_active = FALSE permanently stops generation; existing instances are unaffected.
CREATE TABLE recurring_templates (
    id          UUID               NOT NULL DEFAULT gen_random_uuid(),
    user_id     UUID               NOT NULL,
    title       VARCHAR(255)       NOT NULL,
    description TEXT,
    frequency   recurringfrequency NOT NULL,
    is_active   BOOLEAN            NOT NULL DEFAULT TRUE,
    next_run_at TIMESTAMPTZ        NOT NULL,  -- when the scheduler should create the next instance
    created_at  TIMESTAMPTZ        NOT NULL DEFAULT NOW(),

    CONSTRAINT pk_recurring_templates      PRIMARY KEY (id),
    CONSTRAINT fk_recurring_templates_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);


-- recurring_template_topics
-- Many-to-many join between recurring templates and topics.
-- When a new instance is created, the scheduler copies these rows into task_topics.
CREATE TABLE recurring_template_topics (
    template_id UUID NOT NULL,
    topic_id    UUID NOT NULL,

    CONSTRAINT pk_recurring_template_topics  PRIMARY KEY (template_id, topic_id),
    CONSTRAINT fk_rtt_template               FOREIGN KEY (template_id) REFERENCES recurring_templates (id) ON DELETE CASCADE,
    CONSTRAINT fk_rtt_topic                  FOREIGN KEY (topic_id)    REFERENCES topics              (id) ON DELETE CASCADE
);


-- recurring_instances
-- Links each generated task instance back to its recurring template.
-- One template can have many instances over time.
CREATE TABLE recurring_instances (
    template_id UUID NOT NULL,
    task_id     UUID NOT NULL,

    CONSTRAINT pk_recurring_instances  PRIMARY KEY (template_id, task_id),
    CONSTRAINT fk_ri_template          FOREIGN KEY (template_id) REFERENCES recurring_templates (id) ON DELETE CASCADE,
    CONSTRAINT fk_ri_task              FOREIGN KEY (task_id)     REFERENCES tasks               (id) ON DELETE CASCADE
);


-- ---------------------------------------------------------------------------
-- Triggers
-- ---------------------------------------------------------------------------

-- Automatically updates tasks.updated_at to NOW() on every row update.
CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_tasks_updated_at
    BEFORE UPDATE ON tasks
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at();


-- ---------------------------------------------------------------------------
-- Indexes
-- ---------------------------------------------------------------------------

-- Primary query pattern: fetch active (non-archived) tasks for a user filtered by status.
CREATE INDEX idx_tasks_user_status
    ON tasks (user_id, status, archived);

-- Accelerates the time-window filter queries (today / within 3 days / within a week).
CREATE INDEX idx_tasks_due_date
    ON tasks (due_date);

-- Partial index for the 4am archiving job.
-- Only 'done' tasks are ever candidates for archiving; exclude all others.
CREATE INDEX idx_tasks_done_at
    ON tasks (done_at) WHERE status = 'done';

-- Accelerates topic-to-task lookups (e.g. "show all tasks in topic X").
CREATE INDEX idx_task_topics_topic
    ON task_topics (topic_id);

-- Partial index for the scheduler job that spawns recurring instances.
-- Only active templates need their next_run_at checked; inactive ones are skipped.
CREATE INDEX idx_recurring_next_run
    ON recurring_templates (next_run_at) WHERE is_active = TRUE;

-- Accelerates topic lookups on recurring templates.
CREATE INDEX idx_recurring_template_topics
    ON recurring_template_topics (topic_id);
